Repository anfema/wagtail_to_ion, pull requests merged in 2022-02, with the labels that each got.

#66 Bugfix: Bail out on scaling if video aspect ratio above 21:9
  wagtail_to_ion/ffmpeg_jobs.py
Labels: Bug

#70 Fix close on unopened file
  wagtail_to_ion/tar.py
Labels: Bug

#69 Remove obsolete `fill_contents()` function
  wagtail_to_ion/serializers/pages.py
Labels: Chore

#67 Remove reliance on BASE_URL
  test_proj/settings.py
  wagtail_to_ion/serializers/ion/document.py
  wagtail_to_ion/serializers/ion/image.py
  wagtail_to_ion/serializers/ion/media.py
  wagtail_to_ion/serializers/pages.py
  wagtail_to_ion/serializers/tar.py
Labels: Enhancement

#68 Update Pipfile.lock
  Pipfile.lock
Labels: Chore
